# Generated by Django 4.1.7 on 2023-05-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/products')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('compare_at_price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('estimate_ship_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookThumnailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/thumbnails')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_images', to='book_model.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('background', models.CharField(max_length=7)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='book_model.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='book_model.book')),
            ],
        ),
    ]
