# Generated by Django 4.1.7 on 2023-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='apparel_id',
            new_name='itemType',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
