# Generated by Django 4.1.7 on 2023-04-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('itemType', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
